apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod
  labels:
    app: httpd-pod
spec:
  setHostnameAsFQDN: true
  containers:
    - name: httpd-pod
      image: httpd:latest
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /usr/local/apache2/htdocs
          name: webroot
  volumes:
    - name: webroot
      hostPath: 
        path: /data/webroot
        type: Directory
